version: '3'
services:
  app:
    image: sksks25/docker-node-mongo_app:latest
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
    networks:
      - app-network
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
