services:
  - name: app
    type: web
    env: docker
    plan: free
    dockerfile_path: ./Dockerfile
    envVars:
      - key: MONGO_URI
        value: mongodb://mongo:27017/docker-node-mongo # Use the private service name.
    ports:
      - 3000

  - name: mongo
    type: private_service
    env: docker
    plan: free
    image: mongo:5
    container_name: mongo
    ports:
      - '27017:27017'
    healthCheckCommand: "mongo --eval 'db.runCommand({ connectionStatus: 1 })'"
    dockerfile_path: ./mongo.Dockerfile
