services:
  - name: app
    type: web
    env: docker
    plan: free
    dockerfile_path: ./Dockerfile
    envVars:
      - key: MONGO_URL
        value: mongodb://mongo:27017/docker-node-mongo
    ports:
      - 10000

  - name: mongo
    type: private_service
    env: docker
    plan: free
    dockerfile_path: ./mongo.Dockerfile # Custom Dockerfile for MongoDB
    healthCheckPath: /
    healthCheckCommand: 'echo "MongoDB is up"'
